import * as React from "react";

export const HarmonyIcons = [
  {
    title: "系统UI",
    icons: {
      airplane_fill: "󰄓",
      arrow_clockwise: "󰃇",
      arrow_counterclockwise: "󰃈",
      arrow_counterclockwise_clock: "󰏕",
      arrow_down_right_and_arrow_up_left: "󰃉",
      arrow_right_up_and_square: "󰃋",
      arrow_up_left_and_arrow_down_right: "󰃍",
      arrowshape_turn_up_right_fill: "󰣂",
      battery: "󰄚",
      battery_75percent: "󰙙",
      bell_fill: "󰇑",
      bell_slash: "󰇓",
      bell_slash_fill: "󰇒",
      bluetooth: "󰉔",
      bluetooth_slash: "󰉓",
      bookmark: "󰀊",
      bookmark_filled_on_bookmark: "󰙚",
      brush: "󰀍",
      brush_fill: "󰀌",
      checkmark: "󰀓",
      checkmark_circle: "󰀏",
      checkmark_circle_fill: "󰀎",
      checkmark_square: "󰀒",
      checkmark_square_fill: "󰇚",
      checkmark_square_on_square: "󰀑",
      checkmark_square_on_square_fill: "󰇙",
      circle_viewfinder: "󰄣",
      clean: "󰀖",
      clean_fill: "󰀕",
      dot_grid_1x2: "󰁠",
      dot_grid_2x2: "󰁡",
      externaldrive: "󰃟",
      externaldrive_fill: "󰃞",
      externaldrive_fill_3: "󰄞",
      eye: "󰄠",
      eye_slash: "󰄟",
      flag: "󰆬",
      flashlight_off_fill: "󰀚",
      flashlight_on_fill: "󰀜",
      full_screen_fill: "󰕊",
      gearshape: "󰀠",
      hand_point_up_tap_fill: "󰒄",
      hand_point_up_tap_fill_1: "󰔢",
      hand_point_up_tap_fill_slash: "󰙱",
      hand_tap: "󰒊",
      hand_thumbsup_fill: "󰗗",
      heart: "󰀥",
      heart_fill: "󰀡",
      heart_slash: "󰀤",
      house: "󰀧",
      house_fill: "󰀦",
      label: "󰈈",
      line_viewfinder: "󰀨",
      lock: "󰀈",
      lock_fill: "󰓁",
      lock_filled_arrow_counterclockwise: "󰕼",
      lock_open: "󰓄",
      lock_open_fill: "󰓃",
      magnifyingglass: "󰀩",
      mic: "󰀆",
      mic_fill: "󰌕",
      minus: "󰀬",
      minus_circle: "󰀫",
      minus_magnifyingglass: "󰚀",
      moon_circle_fill: "󰕮",
      moon_fill: "󰀭",
      moon_slash_circle: "󰕯",
      more: "󰕰",
      nfc: "󰓗",
      nfc_fill: "󰓖",
      paperplane: "󰀰",
      paperplane_right_fill: "󰢨",
      pin: "󰀲",
      pin_fill_1: "󰢫",
      plus: "󰀵",
      plus_magnifyingglass: "󰄧",
      plus_square: "󰣃",
      plus_square_on_square_fill: "󰁭",
      power: "󰀶",
      qrcode: "󰄨",
      rays: "󰀷",
      rectangle_and_arrowshape_turn_up_right: "󰃕",
      rectangle_portrait_rotate: "󰀸",
      rectangle_rotate: "󰢭",
      redo: "󰇴",
      save: "󰀻",
      share: "󰀽",
      slider_horizontal_2: "󰁲",
      slider_vertical_3: "󰄪",
      speaker: "󰁄",
      speaker_slash: "󰁃",
      speaker_wave_3: "󰁊",
      speaker_wave_3_slash: "󰖏",
      square_fill_grid_2x2: "󰁋",
      square_grid_2x2: "󰃣",
      star: "󰁎",
      star_fill: "󰀉",
      sun_max: "󰁐",
      sun_max_fill: "󰁏",
      sun_min: "󰁑",
      trash: "󰀁",
      trash_fill: "󰁒",
      undo: "󰇳",
      wifi: "󰀀",
      wifi_slash: "󰚑",
      xmark: "󰁖",
      xmark_circle: "󰁕",
      xmark_circle_fill: "󰁔",
    },
  },
  {
    title: "时间",
    icons: {
      alarm_fill_1: "󰗯",
      calendar: "󰏚",
      calendar_badge_clock: "󰏘",
      calendar_fill: "󰏙",
      clock: "󰏝",
      clock_fill: "󰏜",
      stopwatch_2: "󰗰",
      timer: "󰐆",
      timer_circle_fill: "󰗶",
      worldclock: "󰐊",
      worldclock_fill: "󰐉",
      worldclock_fill_2: "󰗱",
    },
  },
  {
    title: "箭头",
    icons: {
      arrow_clockwise: "󰃇",
      arrow_counterclockwise: "󰃈",
      arrow_counterclockwise_clock: "󰏕",
      arrow_down_circle: "󰢝",
      arrow_down_right_and_arrow_up_left: "󰃉",
      arrow_left: "󰃊",
      arrow_left_circle: "󰚟",
      arrow_right: "󰈱",
      arrow_right_circle: "󰚠",
      arrow_right_up_and_square: "󰃋",
      arrow_up_circle: "󰃌",
      arrow_up_circle_fill: "󰈲",
      arrow_up_left: "󰈳",
      arrow_up_left_and_arrow_down_right: "󰃍",
      arrow_up_to_line: "󰃏",
      arrowshape_3_triangle_path: "󰓵",
      arrowshape_down_to_line_fill: "󰃐",
      arrowshape_turn_up_right_fill: "󰣂",
      arrowshape_up: "󰈽",
      arrowshape_up_fill: "󰈹",
      arrowshape_up_frame_fill: "󰈺",
      arrowshape_up_left_and_arrowshape_down_right: "󰟮",
      arrowshape_up_to_line_fill: "󰀐",
      arrowtriangle_down_fill: "󰈿",
      arrowtriangle_up_fill: "󰉀",
      chevron_down: "󰃛",
      chevron_down_2_circle: "󰛀",
      chevron_down_circle: "󰛁",
      chevron_left: "󰃚",
      chevron_left_2: "󰛂",
      chevron_left_circle: "󰛃",
      chevron_right: "󰃙",
      chevron_right_circle: "󰛄",
      chevron_up: "󰃘",
      chevron_up_2: "󰛆",
      chevron_up_2_circle: "󰛅",
      chevron_up_circle: "󰑟",
      line_below_arrowtriangle_up_circle_fill: "󰐖",
      line_below_arrowtriangle_up_fill: "󰐗",
      paperplane: "󰀰",
      rectangle_and_arrowshape_turn_up_right: "󰃕",
      redo: "󰇴",
      transfer_station: "󰞈",
      undo: "󰇳",
    },
  },
  {
    title: "相机与照片",
    icons: {
      arrow_down_and_rectangle_on_rectangle: "󰐝",
      arrow_up_and_rectangle_on_rectangle: "󰐠",
      camera: "󰑛",
      camera_fill: "󰐸",
      camera_filters_fill: "󰠬",
      capture_smiles: "󰗈",
      circle_lefthalf_inset_filled: "󰁜",
      circle_righthalf_inset_filled: "󰁝",
      dot_video_fill: "󰂂",
      drop: "󰁣",
      drop_bottomrighthalf_inset_filled: "󰄶",
      flower: "󰊄",
      hand_draw: "󰁦",
      heart_square_stack_fill: "󰔔",
      lightbulb: "󰊜",
      lightbulb_slash: "󰊚",
      line_arrowtriangle_2_inward: "󰁨",
      livephoto: "󰗷",
      movie_fill: "󰓒",
      paintpalette: "󰄥",
      picture: "󰀃",
      picture_2: "󰓥",
      picture_damage: "󰓩",
      picture_fill: "󰓪",
      play_video: "󰓮",
      play_video_fill: "󰢬",
      puzzle: "󰒠",
      puzzle_fill: "󰒵",
      rectangle_on_rectangle: "󰒢",
      rectangle_on_rectangle_fill: "󰒡",
      resolution_video: "󰒣",
      scope: "󰒦",
      scope_slash: "󰒥",
      shutter_photo: "󰒯",
      square_slash: "󰒴",
      template: "󰓿",
      template_fill: "󰓾",
      video_fill: "󰂣",
      video_slasj_fill: "󰡁",
      xmark_picture: "󰡂",
      xmark_picture_fill: "󰠡",
    },
  },
  {
    title: "办公文件",
    icons: {
      arrow_right_folder_circle: "󰂺",
      arrow_right_folder_fill: "󰂻",
      book_open_fill: "󰟉",
      book_pages_fill_1: "󰢿",
      briefcase: "󰙟",
      case_fill: "󰙠",
      checkmark_clipboard_fill: "󰆊",
      doc: "󰂽",
      doc_plaintext: "󰃁",
      doc_plaintext_and_pencil: "󰖯",
      doc_plaintext_and_pencil_fill: "󰙩",
      doc_plaintext_fill: "󰃂",
      doc_text: "󰂼",
      doc_text_badge_arrow_up: "󰖱",
      doc_text_badge_checkmark: "󰃄",
      doc_text_badge_magnifyingglass: "󰖳",
      doc_text_fill: "󰂿",
      folder: "󰃅",
      folder_badge_eye: "󰖽",
      folder_badge_plus: "󰀄",
      folder_fill: "󰃆",
      form: "󰆔",
      grid: "󰙰",
      list_square_bill: "󰖿",
      paperclip: "󰄏",
      text_clipboard: "󰆝",
    },
  },
  {
    title: "键盘",
    icons: {
      asterisk_rectangle_badge_handwritten: "󰋮",
      celiakeyboard_elevate: "󰒒",
      celiakeyboard_mechanical: "󰋲",
      celiakeyboard_menu_icon_size: "󰋳",
      delete_left: "󰃝",
      delete_left_fill: "󰕁",
      input_mode: "󰒔",
      keyboard_badge_bihua: "󰌂",
      keyboard_badge_cangjie: "󰌃",
      keyboard_badge_handwritten: "󰌆",
      keyboard_badge_spell: "󰌇",
      keyboard_badge_wubi: "󰌈",
      keyboard_badge_zhuyin: "󰌉",
      keyboard_circle: "󰅲",
      keyboard_onehanded_left: "󰌌",
      keyboard_onehanded_right: "󰌍",
      keyboard_square: "󰌎",
      keyboard_thumbmode: "󰌏",
      onehand: "󰌘",
      selector: "󰌛",
      space_1: "󰌜",
      swipeup_input: "󰌞",
      traditional_square: "󰌢",
      translate: "󰁾",
      translate_c2e: "󰌣",
      translate_e2c: "󰌤",
    },
  },
  {
    title: "媒体",
    icons: {
      backward_end_fill: "󰂦",
      discover_fill: "󰇛",
      fast_forward: "󰙫",
      forward_end_fill: "󰂧",
      gobackward_15: "󰏲",
      gobackward_30: "󰏳",
      goforward_10: "󰏴",
      goforward_15: "󰏵",
      goforward_30: "󰏶",
      headphones_fill: "󰙲",
      identify_song: "󰌻",
      list_interrupt: "󰌼",
      media_center: "󰙼",
      music: "󰂭",
      music_fill: "󰂪",
      music_note_list: "󰂬",
      order_play: "󰂮",
      pause: "󰂱",
      pause_round_triangle_fill: "󰡫",
      play_circle_fill: "󰂲",
      play_fill: "󰂴",
      play_hexagon_fill: "󰠓",
      play_round_rectangle_fill: "󰠔",
      record_circle: "󰂷",
      remove_songlist: "󰍣",
      repeat: "󰂸",
      repeat_1: "󰂹",
      reverse_order: "󰏽",
      service: "󰍥",
      shuffle: "󰂵",
      skip_silence: "󰎻",
    },
  },
  {
    title: "通信",
    icons: {
      beidou_satellite_circle_fill: "󰔖",
      beidou_satellite_fill: "󰚭",
      dial: "󰂁",
      ellipsis_bubble: "󰑳",
      ellipsis_message: "󰂅",
      ellipsis_message_fill: "󰂄",
      envelope: "󰂈",
      envelope_fill: "󰂉",
      envelope_open_fill: "󰂊",
      hd_square_fill: "󰊊",
      message: "󰂏",
      message_badge_gearshape_1: "󰝖",
      message_on_message: "󰂎",
      message_on_message_fill: "󰂍",
      mic: "󰀆",
      mic_circle: "󰌔",
      mic_fill: "󰌕",
      mic_slash: "󰝘",
      mic_slash_fill: "󰌗",
      phone_down_fill: "󰂟",
      phone_fill: "󰂞",
      recordingtape: "󰅶",
      recordingtape_rectangle: "󰅵",
      recordingtape_rectangle_fill: "󰅴",
      satellite: "󰅷",
    },
  },
  {
    title: "连接",
    icons: {
      bluetooth: "󰉔",
      bluetooth_slash: "󰉓",
      dot_radiowaves_left_and_right: "󰉹",
      hotspot: "󰊏",
      icloud: "󰊔",
      icloud_slash: "󰊓",
      icloud_slash_fill: "󰊒",
      link_slash: "󰊠",
      mobiledata: "󰊩",
      nfc: "󰓗",
      nfc_fill: "󰓖",
      wifi: "󰀀",
      wifi_slash: "󰚑",
    },
  },
  {
    title: "符号标识",
    icons: {
      bolt: "󰉢",
      bolt_filled_on_circle: "󰉟",
      bolt_shield_fill: "󰟱",
      exclamationmark: "󰄋",
      exclamationmark_circle: "󰄉",
      exclamationmark_shield_fill: "󰑷",
      exclamationmark_triangle_fill: "󰛗",
      info_circle: "󰊖",
      info_shield: "󰊗",
      nosign: "󰄎",
      questionmark_circle: "󰄀",
    },
  },
  {
    title: "编辑",
    icons: {
      calculator_1: "󰡟",
      character_arrow_clockwise: "󰇖",
      character_viewfinder: "󰇘",
      circle_dashed: "󰄴",
      close_sidebar: "󰢟",
      crop_rotate: "󰅡",
      cut: "󰁟",
      eraser_line: "󰁥",
      indent_right: "󰅣",
      indentation_left: "󰅤",
      list_bullet: "󰁩",
      list_bullet_circle: "󰅦",
      list_bullet_square_fill: "󰅧",
      list_checkmask: "󰅂",
      list_letter: "󰅄",
      list_number: "󰅃",
      list_square: "󰅅",
      open_sidebar: "󰢧",
      paintbrush: "󰟞",
      paintbrush_fill: "󰟝",
      paintpalette_fill: "󰄤",
      pencil_line_1: "󰘦",
      pencil_waveform: "󰁬",
      pencil_waveform_fill: "󰘧",
      rectangle_and_cut: "󰁯",
      rename: "󰁱",
      sort: "󰖁",
      square_and_pencil: "󰁳",
      square_and_pencil_fill: "󰁴",
      swap: "󰋑",
      text_aligncenter: "󰁶",
      text_alignleft: "󰁷",
      text_alignright: "󰁸",
      text_and_arrow_down: "󰁹",
      text_and_arrow_up: "󰁺",
      textformat_size_square: "󰁼",
      transparency_lock: "󰘹",
      trapezoid_and_line_horizontal: "󰅪",
      trapezoid_and_line_vertical: "󰅫",
      triangleshape_fill: "󰍫",
      vertical_flip: "󰘻",
    },
  },
  {
    title: "隐私&安全",
    icons: {
      checkmark_shield: "󰑞",
      checkmark_shield_fill: "󰑝",
      eye: "󰄠",
      eye_slash: "󰄟",
      hand_raised_hexagon: "󰝃",
      hand_raised_hexagon_fill: "󰒇",
      key_horizontal: "󰒛",
      key_shield: "󰒞",
      key_shield_fill: "󰒝",
      lock: "󰀈",
      lock_fill: "󰓁",
      lock_open: "󰓄",
      lock_open_fill: "󰓃",
      nearlink: "󰝜",
      person_shield: "󰓞",
      person_shield_fill: "󰓝",
      staroflife_rectangle: "󰓸",
      touchid: "󰔇",
      vpn_key: "󰞏",
    },
  },
  {
    title: "人物",
    icons: {
      children: "󰙣",
      ear: "󰗉",
      face: "󰗊",
      face_smiling: "󰗐",
      figure_arms_open: "󰗑",
      figure_running: "󰟕",
      hand_point_up_tap_fill: "󰒄",
      hand_point_up_tap_fill_1: "󰔢",
      hand_point_up_tap_fill_slash: "󰙱",
      hand_tap: "󰒊",
      person: "󰗥",
      person_2: "󰗜",
      person_2_fill: "󰗛",
      person_badge_plus: "󰗟",
      person_crop_circle_fill_1: "󰗳",
      person_filled_badge_plus: "󰗤",
      person_filled_viewfinder: "󰕹",
      person_square_fill: "󰕺",
      portrait: "󰗇",
    },
  },
  {
    title: "形状",
    icons: {
      circle: "󰀇",
      oval: "󰍋",
      rectangle: "󰁰",
      rectangle_split_3x1: "󰔨",
      rotate_left: "󰍤",
      smallcircle_filled_circle: "󰅩",
      square: "󰁵",
    },
  },
  {
    title: "交通出行",
    icons: {
      local_fill: "󰆸",
      location_north_up_right_circle_fill: "󰠍",
      map: "󰇂",
      map_badge_local: "󰇀",
      map_slash: "󰇃",
      navigation: "󰠐",
      position: "󰇊",
      route_plan: "󰟤",
      satellite_map: "󰝵",
      satellite_map_fill: "󰝴",
    },
  },
];

export default HarmonyIcons.reduce((acc, cur) => {
  const icons = cur.icons;
  Object.keys(icons).forEach((iconName) => {
    acc[iconName] = icons[iconName];
  });
  return acc;
}, {});
